### ISSUE TITLE
Secret parameters

### ISSUE THREAD

**Issue by s1l0uk** [cotdsa/cumulus#5]
Hi Guys, Love the work so far and enjoying playing with this. Just a silly question...

With the idea that we can build infrastructure in to config files, do you have a way to put a secret in to the mix? for example a Password? 

Would this have to be declared in plain text in the YAML configuration file or do you guys have a way of preventing this information leaking in to SCM when people are making configs for Cumulus use?

Many thanks in advance and keep up the good work!
Thanks,
//P

**Comment by acaire** [comment]
Closing this one for now.
